-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the ref you want to point at
    hooks:
    -   id: file-contents-sorter
        args: ["--unique", "filenames=sanitär.txt"]
